### ISSUE TITLE
Trying to install 

### ISSUE THREAD

**Issue by Villelmo** [HadesNull123/xvideos#1]
Traceback (most recent call last):
  File "app.py", line 2, in <module>
    from utils.downloadXvideos import download_xvideos
  File "/home/lulu/xvideos/utils/downloadXvideos.py", line 29
    print download_xvideos('https://www.xvideos.com/video37601777/cumteshots_at_fantasy_fucking_orgy')  # noqa

SyntaxError: invalid syntax

_Python 2.7.16 (default, Oct 10 2019, 22:02:15) 
[GCC 8.3.0] on linux2_

**Comment by HadesNull123** [comment]
You can run it with python 2.
If necessary, I can help you with teamview. Please contact me from 9AM - 5PM. GMT +7.

**Comment by Villelmo** [comment]
> You can run it with python 2.
> If necessary, I can help you with teamview. Please contact me from 9AM - 5PM. GMT +7.

You can configure your time zone in GitHub
